package lab4;

import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.Comparator;
import core.AbstractSwappingSortingAlgorithm;
import testing.*;
import testing.comparators.*;
import testing.generation.*;
import testing.generation.conversion.*;

public class SortingTester {
    public static void main(String[] args) {
        int[] arraySizes = {0, 5, 10, 15, 20, 30, 40, 50, 60, 70, 80, 100, 150, 200, 250, 500, 1000, 2000, 5000, 10000};

        Comparator<MarkedValue<Integer>> markedComparator = new MarkedValueComparator<Integer>(new IntegerComparator());

        Generator<MarkedValue<Integer>> orderedGenerator = new MarkingGenerator<Integer>(new OrderedIntegerArrayGenerator());
        Generator<MarkedValue<Integer>> reversedGenerator = new MarkingGenerator<Integer>(new ReversedIntegerArrayGenerator());
        Generator<MarkedValue<Integer>> randomGenerator = new MarkingGenerator<Integer>(new RandomIntegerArrayGenerator(10));
        Generator<MarkedValue<Integer>> shuffledGenerator = new MarkingGenerator<Integer>(new ShuffledIntegerArrayGenerator(10));

        AbstractSwappingSortingAlgorithm<MarkedValue<Integer>> algorithm = new BinaryInsertionSort<>(markedComparator);
        testSort("BinarySort", algorithm, markedComparator, orderedGenerator, arraySizes, "OrderedGenerator");
        testSort("BinarySort", algorithm, markedComparator, reversedGenerator, arraySizes, "ReversedGenerator");
        testSort("BinarySort", algorithm, markedComparator, randomGenerator, arraySizes, "RandomGenerator");
        testSort("BinarySort", algorithm, markedComparator, shuffledGenerator, arraySizes, "ShuffledGenerator");

        algorithm = new CocktailShakerSort<>(markedComparator);
        testSort("CocktailSort", algorithm, markedComparator, orderedGenerator, arraySizes, "OrderedGenerator");
        testSort("CocktailSort", algorithm, markedComparator, reversedGenerator, arraySizes, "ReversedGenerator");
        testSort("CocktailSort", algorithm, markedComparator, randomGenerator, arraySizes, "RandomGenerator");
        testSort("CocktailSort", algorithm, markedComparator, shuffledGenerator, arraySizes, "ShuffledGenerator");

        algorithm = new SelectionSortWithMax<>(markedComparator);
        testSort("SelectionSort", algorithm, markedComparator, orderedGenerator, arraySizes, "OrderedGenerator");
        testSort("SelectionSort", algorithm, markedComparator, reversedGenerator, arraySizes, "ReversedGenerator");
        testSort("SelectionSort", algorithm, markedComparator, randomGenerator, arraySizes, "RandomGenerator");
        testSort("SelectionSort", algorithm, markedComparator, shuffledGenerator, arraySizes, "ShuffledGenerator");
    }


    private static void testSort(String sortType, AbstractSwappingSortingAlgorithm<MarkedValue<Integer>> algorithm, Comparator<MarkedValue<Integer>> markedComparator, Generator<MarkedValue<Integer>> generator, int[] arraySizes, String generatorType) {

        String fileName = sortType + generatorType + ".txt";

        try (PrintWriter writer = new PrintWriter(new FileWriter(fileName))) {
            writer.println("-- " + sortType + " test; numbers generated by: " + generatorType + " --");
            writer.println("Size\tTime\t\tStddev\t\tCompare\t\tStddev\t\tSwaps\t\tStddev");

            for (int size : arraySizes) {
                testing.results.swapping.Result result = Tester.runNTimes(algorithm, generator, size, 50);
                String formattedOutput = String.format("%5d\t%f\t%f\t%f\t%f\t%f\t%f", size,
                        result.averageTimeInMilliseconds(), result.timeStandardDeviation(),
                        result.averageComparisons(), result.comparisonsStandardDeviation(),
                        result.averageSwaps(), result.swapsStandardDeviation());

                writer.print(formattedOutput.replace('.', ',') + "\n");
            }

            System.out.println("Zapisano wyniki do pliku " + fileName);
        } catch (Exception e) {
            System.err.println("Wystąpił błąd podczas zapisywania wyników do pliku: " + e.getMessage());
        }
    }
}
